### ISSUE TITLE
Does this only work for promises constructed with the Promise global?

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/loud-rejection#10]
I just discovered that an error from [rollup](https://github.com/rollup/rollup) was being swallowed, even though I was using loud-rejection.

It looks like rollup uses [es6-promise](https://github.com/jakearchibald/es6-promise) instead of the builtin `Promise`. Does this mean loud-rejection only works for promises constructed from the `Promise` global, and can't be made to work for other ones?

**Comment by jamestalmage** [comment]
It works for any Promise library that emits `unhandledRejection` on `process`. Ask the `es6-promise` folks to implement.

**Comment by sindresorhus** [comment]
Both [pinkie-promise](https://github.com/floatdrop/pinkie-promise) and [bluebird](https://github.com/petkaantonov/bluebird) supports it. Unsure about others. `pinkie-promise` is tiny and fully compliant. Just do a pull request on Rollup to use that instead.

**Comment by jamestalmage** [comment]
:+1: Better idea. It looks like `es6-promise` has a browser focus, so they may not be interested in supporting Node events.

**Comment by TrySound** [comment]
@callumlocke Bluebird is better. Pinkie fails on windows

**Comment by jamestalmage** [comment]
> Bluebird is better. Pinkie fails on windows

That's news to me. File an issue with a reproduction and we will fix it.

**Comment by sindresorhus** [comment]
@TrySound Bluebird is different. It's better if you have a large project and needs lots of utilities. Pinkie is tiny and great for use in small modules. As for the Windows comment, please provide some proof, preferably as a ticket on the `pinkie` issue tracker.

**Comment by TrySound** [comment]
@sindresorhus https://ci.appveyor.com/project/davidtheclark/cosmiconfig/history
Something wrong was with ava in those tests. There was 22 at all. But 22 was passed and 9 was failed on node 0.10. Bluebird is passed fine there.

**Comment by TrySound** [comment]
@jamestalmage We couldn't reproduce it :) But appveyor was failed.

**Comment by sindresorhus** [comment]
@TrySound Still better to open an issue than to complain elsewhere without any actual proof. AppVeyor is consistently flaky, the fact that the switch fixed it could have just been a coincidence.

**Comment by jamestalmage** [comment]
And as I recall, you were using https://github.com/floatdrop/pinkie/pull/11 before we decided to go with https://github.com/floatdrop/pinkie/pull/12

**Comment by TrySound** [comment]
@jamestalmage You are right. Seems like it was `cache:  - node_modules` appveyor settings. 
https://github.com/davidtheclark/cosmiconfig/pull/19
Maybe remove it at all?

**Comment by sindresorhus** [comment]
@TrySound Yes, not worth the possible trouble. And you would always want to test on latest sub-dependencies anyways.

> There are only two hard things in Computer Science: cache invalidation and naming things.
> \- Phil Karlton.

**Comment by TrySound** [comment]
@sindresorhus True. Thanks!
