### ISSUE TITLE
Does not work with `process.exit()`

### ISSUE THREAD

**Issue by julien-f** [sindresorhus/loud-rejection#13]
```js
require('loud-rejection/register')

console.log('foo')
Promise.reject(new Error('bar'))

process.exit()
```

Give:

```
> node index.js
foo
>
````

**Comment by julien-f** [comment]
With Node 4.2.2 and loud-rejection 1.2.0.

**Comment by sindresorhus** [comment]
Sounds like a problem with [`signal-exit`](https://github.com/bcoe/signal-exit). Can you check if https://github.com/sindresorhus/loud-rejection/blob/ae879160aab7799459e513226cb869870467aeee/index.js#L26 is ever called?

**Comment by julien-f** [comment]
It is correctly called.

**Comment by julien-f** [comment]
Waiting a complete turn of the event loop seems to resolve the problem.

```js
require('loud-rejection/register')

Promise.reject(new Error('foo'))

setImmediate(function () { // Not process.nextTick()!
  process.exit(1)
})
```

I think it is not a bug but a normal behaviour of how unhandled rejected promises are detected.

**Comment by jamestalmage** [comment]
> I think it is not a bug but a normal behaviour of how unhandled rejected promises are detected.

That is correct. This is actually well defined [in the spec](https://nodejs.org/api/process.html#process_event_unhandledrejection):

> ## Event: 'unhandledRejection'
> Emitted whenever a Promise is rejected and no error handler is attached to the promise **within a turn of the event loop** 
> (*ea*)

**Comment by sindresorhus** [comment]
@jamestalmage Maybe we could use the `process.on('beforeExit')` event to prolong the process another event loop so it just works?

**Comment by jamestalmage** [comment]
I tried, see #14.

I just don't think this is doable.

**Comment by leo** [comment]
https://github.com/sindresorhus/loud-rejection/pull/14#issuecomment-167789675

**Comment by jamestalmage** [comment]
Unless the spec for `unhandledRejection` changes, this just isn't doable. I am closing.
