### ISSUE TITLE
Can/should loud-rejection be used in the browser?

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/loud-rejection#16]
1. does it work in the browser?
2. is it necessary in the browser?

**Comment by sindresorhus** [comment]
1. No, the browser uses slightly different naming for the events.
2. https://github.com/sindresorhus/loud-rejection/commit/273a7c04aba656f23ee07714df821e8531a2e723

**Comment by callumlocke** [comment]
thanks!

You said browsers automatically log unhandled exceptions.. is this true only for the browser's built-in `Promise` type, or does this (somehow) work for stuff like es6-promise, bluebird too?

**Comment by jamestalmage** [comment]
Should there be a noop `browser.js` alternative so people can easily browserify?

I usually use loud-rejection as part of `cli.js` so I don't think I would ever browserify it.

**Comment by sindresorhus** [comment]
> is this true only for the browser's built-in Promise type, or does this (somehow) work for stuff like es6-promise, bluebird too?

It's true for any Promise lib that emits the correct events, at least Bluebird does this.

> Should there be a noop browser.js alternative so people can easily browserify?

Yeah, sure, just in case.
