### ISSUE TITLE
Breaking change between minor versions

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/loud-rejection#19]
After a long debugging session I ended up in the loud-rejection source and found that its behaviour has [completely changed](https://github.com/sindresorhus/loud-rejection/pull/5) since v1.0.0:

- [v1.0.0](https://github.com/sindresorhus/loud-rejection/blob/v1.0.0/index.js): if a promise goes unhandled, kill the process.
- [v1.1.0](https://github.com/sindresorhus/loud-rejection/blob/v1.1.0/index.js): if a promise goes unhandled, keep track of it in a secret array which is only printed out _if and when_ the process exits for some other reason.

The first problem is, this should have been a major version bump. It's a backwards-incompatible change that has broken a lot of my server apps, which expected the process to exit if a promise goes unhandled (just as it does when an exception goes uncaught).

Second, it means loud-rejection is no longer appropriate for a whole set of use cases, such as server apps, or anything else that is supposed to run indefinitely. Contrived example (which behaves completely differently after the minor bump to `v1.1.0`):

```js
import 'loud-rejection/register';
import express from 'express';

const app = express();

app.get('/', async function (req, res) {
  console.log('something');
  if (x) throw new Error('foo');

  res.send('hi');
});
```

In the above code, here's what happens when a browser requests `http://localhost/` when `x` is truthy: the server app logs `"something"` and then the request just hangs forever – the 'foo' error is never logged, despite loud-rejection having been registered. You can refresh the browser several times and you just see `"something"` logged again and again. Later, when you manually kill the process with `ctrl+C`, only then do you see all the 'foo' errors printed out.

Finally, in my opinion this change shouldn't have been made at all, even with a major bump. In my experience, the only times I've ever wanted to swoop in and attach an error handler to an already-rejected promise are when I'm doing some horrible hack that I shouldn't be doing. It's an antipattern. If you think you want to leave a promise unhandled until you _maybe_ inspect its outcome later, then what you really want is to catch it and store the success/failure information in a variable for later inspection. Or you could 'settle' the promise's outcome into something inspectable (using e.g. Bluebird's [`.reflect()`](http://bluebirdjs.com/docs/api/reflect.html) or just `p.then(x, y).then(settled => {...})`). A rejection is supposed to be the async analog to an exception, it shouldn't go uncaught unless you want it to be fatal.

**Comment by jamestalmage** [comment]
That behavior actually changed [here](https://github.com/sindresorhus/loud-rejection/pull/3). 

Agreed that it should probably have been a major bump. Sorry.

However, I disagree on your usage scenario. It's perfectly acceptable to have temporarily unhandled rejections, as long as you get around to handling them eventually.

If you want to kill the process the first time a rejection goes unhandled, just do: 

```js
process.on('unhandledRejection', () => process.exit(1));
```

**Comment by callumlocke** [comment]
> Agreed that it should probably have been a major bump. Sorry.

No worries, I've done the same before :) sorry for the ranty tone of my post.

> If you want to kill the process the first time a rejection goes unhandled, just do:
> 
> ```js
> process.on('unhandledRejection', () => process.exit(1));
> ```

It's a bit more effort than though, you also need to do all this, which is why I liked using loud-rejection:

```js
process.on('unhandledRejection', err => {
  if (err instanceof Error) {
    console.error(err.stack);
  } else if (err) {
    console.error('Promise rejected with value:', err);
  } else {
    console.error('Promise rejected no value');
  }

  process.exit(1);
});
```

> It's perfectly acceptable to have temporarily unhandled rejections, as long as you get around to handling them eventually.

I'm not sure about this. How can anything know if you're going to get around to handling them eventually? Waiting until the end of the process works in some cases, but it is not an option for apps that have no natural 'end', like servers and daemons – these apps will just continue trying to serve requests indefinitely even after something has permanently broken, like in the snippet in my original post. The one and only way to indicate that you're going to handle a promise, is to handle it now. It is always possible to do this – if you want to inspect the outcome later, asynchronously, that's fine. It doesn't mean you have to leave a shroedinger's promise lying around. You just need to settle it now and record its outcome in a variable for later inspection.

I accept there are cases where you wouldn't want a dangling rejection to kill your process, but I think in those cases you shouldn't be using loud-rejection. The whole point of using loud-rejection is to opt into a stricter system, where rejections behave like exceptions – fail to handle them, and your app dies with a stack trace.

I can see the value of the new behaviour for some cases, but I think it would make more sense as an option, something like `require('loud-rejection').register({ waitUntilExit: true })`.

**Comment by callumlocke** [comment]
> If you have dependencies, you can't be sure that none of them will ever hold a promise in an unhandled state (even for a moment)

That is a very good point. Haven't run into that but it could be a problem with some libraries.

Ok it sounds like you're committed to the report-on-exit approach, which is cool, in that case can I suggest it should be made very clear in the readme that it doesn't
