### ISSUE TITLE
Should I use this in tests?

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/loud-rejection#2]
README.md:

> **Should NOT be used in reusable modules. Only in top-level apps / CLI tools.**

That makes sense. But what about using it in *tests* for reusable modules?

For example, mocha now lets me [return a promise](https://mochajs.org/#working-with-promises). But let's say I forget to actually type `return`, so I just have a loose promise:

```js
it('does something', function () {
  foo().then(function (result) {
     assert(result.isGood);
  });
});
```

..the test passes immediately, then some time later my promise silently fails.

Would you recommend calling loud-rejection at the top of any test script?

**Comment by sindresorhus** [comment]
Yes, tests are a good use-case for this. I've improved the wording in the readme.

Though, ideally, the test runner should take care of this for you. I'm planning on [integrating](https://github.com/sindresorhus/ava/issues/80) this into AVA.

**Comment by codeinabox** [comment]
How would I use this with Karma? I am trying to integrate this into a [Webpack test context](https://github.com/insin/nwb/blob/master/docs/Testing.md#using-a-test-context-module) but it's not causing my tests to fail as I would expect. Effectively I am trying to track down some `ERROR: 'Unhandled promise rejection', TypeError{}` errors.

```js
const loudRejection = require('loud-rejection');

beforeEach(() => {
  loudRejection(() => fail());
});

const context = require.context('./tests', true, /\.jsx?$/);
context.keys().forEach(context);
```

**Comment by jamestalmage** [comment]
This is not a browser ready module.

A karma plugin would use entirely different hooks, both for capturing rejections, and reporting them to the user.

It's a good idea, but it would almost certainly be a separate thing.

`karma-ava` should have it built in, but I haven't tried to make it work with Webpack yet (all testing was via browserify).
