### ISSUE TITLE
error logs only at exit

### ISSUE THREAD

**Issue by magicdawn** [sindresorhus/loud-rejection#23]
## env

```
$ node -p 'process.versions'
{ http_parser: '2.7.0',
  node: '7.6.0',
  v8: '5.5.372.40',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }

$ npm -v
4.1.2
```

## example code

```js
'use strict'

require('loud-rejection/register')

async function main(){
  throw new Error('boom')
}

main()

setTimeout(function() {
  // none
}, 20000000);
```

## behaviors

```
$ node index.js
^CError: boom
    at main (/Users/magicdawn/projects/001_learn/node/index.js:6:9)
    at Object.<anonymous> (/Users/magicdawn/projects/001_learn/node/index.js:9:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
```

the boom stack prints after I press `Ctrl+C` kill the process.

**Comment by magicdawn** [comment]
Looks like it's designed to print unhandled rejections at exit. 

> If any remain unhandled at the end of your process, it logs them to STDERR.

Sorry.

**Comment by sindresorhus** [comment]
Sounds like you want `hard-rejection` instead. See the readme.

**Comment by magicdawn** [comment]
Oh just wanna find a module do `process.on('unhandledRejection', err => console.error(e.stack || e))` for me~ I had wrote too much this 😂 
Thanks

**Comment by vjpr** [comment]
@sindresorhus This module does fails silently in contradiction to its description and name.

I think most people would think that this module is going to print a big error message when there is a rejection. I don't know another way to read this and for the current functionality to make sense:

> Make unhandled promise rejections fail loudly instead of the default silent fail

What is the reason for not printing an error message?

**Comment by sindresorhus** [comment]
@vjpr No, it's just that it doesn't fail loudly until the process exits. That's done to adhere to how promises work. Promises are allowed to be uncaught and then later caught asynchronously. So if we would fail loudly right away, we would have a lot of false positives. As commented above, if you still want that behavior, see my `hard-rejection` module.

**Comment by vjpr** [comment]
I would suggest modifying the description to:

> Make unhandled promise rejections fail loudly (when the process exits) instead of the default silent fail

I've been caught out so many times by thinking this module was the same as what @magicdawn wanted. And instead of thinking that the `loud-rejection` module behaved like it does, I would think something else was blocking the errors.
