### ISSUE TITLE
Use of the "unhandledRejection" event.

### ISSUE THREAD

**Issue by infacto** [sindresorhus/loud-rejection#30]
Why not just add the event `unhandledRejection`? No lib/dep required. While newer NodeJS versions will handle it automatically.

```js
process.on('unhandledRejection', ex => {
  console.error(ex);
  // Optional throw an error / terminate the process.
  process.exit(1);
});
```

> DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

https://nodejs.org/api/process.html#process_event_unhandledrejection

**Comment by sindresorhus** [comment]
Your code will exit right away on an unhandled rejection, this package will only error at the end of the process lifetime if any unhandled rejections were emitted during the lifetime of the process. This is documented at the top of the readme.
