### ISSUE TITLE
Add a 'register' script

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/loud-rejection#6]
It would be nice if there was a `register.js` script in the root so we could do this:

```js
import 'loud-rejection/register';
```

**Comment by sindresorhus** [comment]
Why? It already applies globally.

**Comment by callumlocke** [comment]
Cleaner alternative for people using ES2015 style importing.

```js
import 'loud-rejection/register';

// vs

import loudRejection from 'loud-rejection';
loudRejection();
```

I think it's a nice convention for anything that registers a global side-effect. I've seen a few modules use this style, including:

```js
import 'babel-core/register';
import 'coffee-script/register';
```

**Comment by sindresorhus** [comment]
I don't like that pattern, but I'll merge if you do the work.

**Comment by callumlocke** [comment]
ok :) what is it you don't like about it? (just in case your answer stops me wanting it)

**Comment by sindresorhus** [comment]
I don't like side-effecting imports. It feels dirty. The reason I'm oking this is that it's at least explicit with the `/register`.

**Comment by callumlocke** [comment]
I agree side-effecting imports feel dirty. But then again, so do side-effecting function calls like `loudRejection()`.

In fact I'd argue that the fromless-import style is less dirty than a function call, because it's a syntax specifically designed for side-effects: with `import 'foo'` (as opposed to `import foo from 'foo'`) it's obvious just from the syntax that the line has some kind of global side effect.

Anyway, if you're oking it, I'll do it!

**Comment by sindresorhus** [comment]
:+1: Make sure to update the readme too.

**Comment by LinusU** [comment]
I've been against this as well but I kind of like your reasoning, thanks for enlighten me :)

**Comment by jamestalmage** [comment]
:+1:
