### ISSUE TITLE
Option to exit without modifying the exit code. 

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/loud-rejection#8]
Right now `loud-rejection` forces a non-zero exit code.

When used in test runners that fork processes (i.e. AVA), that may not be the desired outcome.

Mocha (for example), does not fail tests due to unhandledRejections, but it does print. them.

**Comment by sindresorhus** [comment]
How is it not the desired outcome? Do you have an actual use-case for this? Unhandled rejections are errors and should IMHO exit as such.

**Comment by jamestalmage** [comment]
If you are writing tests that specifically deal with unhandled rejections.

**Comment by sindresorhus** [comment]
Ok, but let's just do it undocumented for now.

**Comment by jamestalmage** [comment]
Actually, I think the API covers this. So I'm closing
